services:
  api:
    build: .
    image: rumi-image
    container_name: rumi-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/rumi-db
      SPRING_DATASOURCE_USERNAME: rumi-user
      SPRING_DATASOURCE_PASSWORD: rumirumi
      RUMI_API_HOST: https://rumiapi.cekrek.shop
      CONSUMET_API_HOST: http://consumet
  db:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: rumi-user
      POSTGRES_PASSWORD: rumirumi
      POSTGRES_DB: rumi-db
    volumes:
      - postgres-data:/var/lib/postgres/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@local.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  consumet:
    image: riimuru/consumet-api:latest
    container_name: consumet-container
    restart: always
    ports:
      - "3000:80"
    environment:
      PORT: 80

volumes:
  postgres-data:
  pgadmin-data: